services:
  - type: web
    name: user-tracker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: MONGODB_URI
        sync: false
